//
// EmbyMediaModelTypesLevelInformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmbyMediaModelTypesLevelInformation: Codable {

    public var shortName: String?
    public var _description: String?
    public var ordinal: Int?
    public var maxBitRate: EmbyMediaModelTypesBitRate?
    public var maxBitRateDisplay: String?
    public var _id: String?
    public var resolutionRates: [EmbyMediaModelTypesResolutionWithRate]?
    public var resolutionRateStrings: [String]?
    public var resolutionRatesDisplay: String?

    public init(shortName: String? = nil, _description: String? = nil, ordinal: Int? = nil, maxBitRate: EmbyMediaModelTypesBitRate? = nil, maxBitRateDisplay: String? = nil, _id: String? = nil, resolutionRates: [EmbyMediaModelTypesResolutionWithRate]? = nil, resolutionRateStrings: [String]? = nil, resolutionRatesDisplay: String? = nil) {
        self.shortName = shortName
        self._description = _description
        self.ordinal = ordinal
        self.maxBitRate = maxBitRate
        self.maxBitRateDisplay = maxBitRateDisplay
        self._id = _id
        self.resolutionRates = resolutionRates
        self.resolutionRateStrings = resolutionRateStrings
        self.resolutionRatesDisplay = resolutionRatesDisplay
    }

    public enum CodingKeys: String, CodingKey { 
        case shortName = "ShortName"
        case _description = "Description"
        case ordinal = "Ordinal"
        case maxBitRate = "MaxBitRate"
        case maxBitRateDisplay = "MaxBitRateDisplay"
        case _id = "Id"
        case resolutionRates = "ResolutionRates"
        case resolutionRateStrings = "ResolutionRateStrings"
        case resolutionRatesDisplay = "ResolutionRatesDisplay"
    }

}
