//
// MarkerType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum MarkerType: String, Codable {
    case chapter = "Chapter"
    case introStart = "IntroStart"
    case introEnd = "IntroEnd"
    case creditsStart = "CreditsStart"
}