//
// TasksTaskInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TasksTaskInfo: Codable {

    public var name: String?
    public var state: TasksTaskState?
    public var currentProgressPercentage: Double?
    public var _id: String?
    public var lastExecutionResult: TasksTaskResult?
    public var triggers: [TasksTaskTriggerInfo]?
    public var _description: String?
    public var category: String?
    public var isHidden: Bool?
    public var key: String?

    public init(name: String? = nil, state: TasksTaskState? = nil, currentProgressPercentage: Double? = nil, _id: String? = nil, lastExecutionResult: TasksTaskResult? = nil, triggers: [TasksTaskTriggerInfo]? = nil, _description: String? = nil, category: String? = nil, isHidden: Bool? = nil, key: String? = nil) {
        self.name = name
        self.state = state
        self.currentProgressPercentage = currentProgressPercentage
        self._id = _id
        self.lastExecutionResult = lastExecutionResult
        self.triggers = triggers
        self._description = _description
        self.category = category
        self.isHidden = isHidden
        self.key = key
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case state = "State"
        case currentProgressPercentage = "CurrentProgressPercentage"
        case _id = "Id"
        case lastExecutionResult = "LastExecutionResult"
        case triggers = "Triggers"
        case _description = "Description"
        case category = "Category"
        case isHidden = "IsHidden"
        case key = "Key"
    }

}
