//
// UpdatesPackageVersionClass.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum UpdatesPackageVersionClass: String, Codable {
    case release = "Release"
    case beta = "Beta"
    case dev = "Dev"
}