// <copyright file="EncodingInfoServiceApi.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Api
{
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Linq;
    using System.Threading.Tasks;
	using RestSharp;
	using Emby.ApiClient.Client;
	using Emby.ApiClient.Model;

    /// <summary>
    /// Provides a collection of service methods to interact with the API endpoints.
    /// </summary>
    public partial class EncodingInfoServiceApi : IApiAccessor
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingInfoServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EncodingInfoServiceApi(ApiClient apiClient)
        {
            this.ApiClient = apiClient;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.ApiClient.RestClient.Options.BaseUrl?.ToString();
        }

        /// <summary>Gets the ApiClient object</summary>
        /// <value>An instance of the ApiClient</value>
        public ApiClient ApiClient {get; }

        /// <summary>
        /// Gets default codec configurations
        /// </summary>
        /// <remarks>
        /// Requires authentication as administrator
        /// </remarks>
        /// <returns>Task of ApiResponse (List&lt;CodecConfiguration&gt;)</returns>
        public async Task<RestResponse<List<CodecConfiguration>>> GetEncodingCodecconfigurationDefaults ()
        {
            var request = new RestRequest("/Encoding/CodecConfiguration/Defaults", Method.Get);

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<List<CodecConfiguration>>(request).ConfigureAwait(false);
            return localVarResponse;
        }

        /// <summary>
        /// Gets details about available video encoders and decoders
        /// </summary>
        /// <remarks>
        /// Requires authentication as administrator
        /// </remarks>
        /// <returns>Task of ApiResponse (List&lt;VideoCodecBase&gt;)</returns>
        public async Task<RestResponse<List<VideoCodecBase>>> GetEncodingCodecinformationVideo ()
        {
            var request = new RestRequest("/Encoding/CodecInformation/Video", Method.Get);

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<List<VideoCodecBase>>(request).ConfigureAwait(false);
            return localVarResponse;
        }

        /// <summary>
        /// Gets available tone mapping options
        /// </summary>
        /// <remarks>
        /// Requires authentication as administrator
        /// </remarks>
        /// <returns>Task of ApiResponse (ConfigurationToneMappingToneMapOptionsVisibility)</returns>
        public async Task<RestResponse<ConfigurationToneMappingToneMapOptionsVisibility>> GetEncodingTonemapoptions ()
        {
            var request = new RestRequest("/Encoding/ToneMapOptions", Method.Get);

            // make the HTTP request
            var localVarResponse = await this.ApiClient.RestClient.ExecuteAsync<ConfigurationToneMappingToneMapOptionsVisibility>(request).ConfigureAwait(false);
            return localVarResponse;
        }

    }
}
