# coding: utf-8

"""
    Emby Server REST API (BETA)

    API version: 4.8.0.6
"""

import pprint
import re  # noqa: F401

import six

class DlnaContainerProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'DlnaDlnaProfileType',
        'conditions': 'list[DlnaProfileCondition]',
        'container': 'str'
    }

    attribute_map = {
        'type': 'Type',
        'conditions': 'Conditions',
        'container': 'Container'
    }

    def __init__(self, type=None, conditions=None, container=None):  # noqa: E501
        """DlnaContainerProfile - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._conditions = None
        self._container = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if conditions is not None:
            self.conditions = conditions
        if container is not None:
            self.container = container

    @property
    def type(self):
        """Gets the type of this DlnaContainerProfile.  # noqa: E501


        :return: The type of this DlnaContainerProfile.  # noqa: E501
        :rtype: DlnaDlnaProfileType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DlnaContainerProfile.


        :param type: The type of this DlnaContainerProfile.  # noqa: E501
        :type: DlnaDlnaProfileType
        """

        self._type = type

    @property
    def conditions(self):
        """Gets the conditions of this DlnaContainerProfile.  # noqa: E501


        :return: The conditions of this DlnaContainerProfile.  # noqa: E501
        :rtype: list[DlnaProfileCondition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this DlnaContainerProfile.


        :param conditions: The conditions of this DlnaContainerProfile.  # noqa: E501
        :type: list[DlnaProfileCondition]
        """

        self._conditions = conditions

    @property
    def container(self):
        """Gets the container of this DlnaContainerProfile.  # noqa: E501


        :return: The container of this DlnaContainerProfile.  # noqa: E501
        :rtype: str
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this DlnaContainerProfile.


        :param container: The container of this DlnaContainerProfile.  # noqa: E501
        :type: str
        """

        self._container = container

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DlnaContainerProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DlnaContainerProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
