# coding: utf-8

"""
    Emby Server REST API (BETA)
"""

import pprint
import re  # noqa: F401

import six

class CopyData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'to_user_ids': 'list[str]',
        'copy_options': 'list[LibraryUserCopyOptions]'
    }

    attribute_map = {
        'user_id': 'UserId',
        'to_user_ids': 'ToUserIds',
        'copy_options': 'CopyOptions'
    }

    def __init__(self, user_id=None, to_user_ids=None, copy_options=None):  # noqa: E501
        """CopyData - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._to_user_ids = None
        self._copy_options = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if to_user_ids is not None:
            self.to_user_ids = to_user_ids
        if copy_options is not None:
            self.copy_options = copy_options

    @property
    def user_id(self):
        """Gets the user_id of this CopyData.  # noqa: E501


        :return: The user_id of this CopyData.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this CopyData.


        :param user_id: The user_id of this CopyData.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def to_user_ids(self):
        """Gets the to_user_ids of this CopyData.  # noqa: E501


        :return: The to_user_ids of this CopyData.  # noqa: E501
        :rtype: list[str]
        """
        return self._to_user_ids

    @to_user_ids.setter
    def to_user_ids(self, to_user_ids):
        """Sets the to_user_ids of this CopyData.


        :param to_user_ids: The to_user_ids of this CopyData.  # noqa: E501
        :type: list[str]
        """

        self._to_user_ids = to_user_ids

    @property
    def copy_options(self):
        """Gets the copy_options of this CopyData.  # noqa: E501


        :return: The copy_options of this CopyData.  # noqa: E501
        :rtype: list[LibraryUserCopyOptions]
        """
        return self._copy_options

    @copy_options.setter
    def copy_options(self, copy_options):
        """Sets the copy_options of this CopyData.


        :param copy_options: The copy_options of this CopyData.  # noqa: E501
        :type: list[LibraryUserCopyOptions]
        """

        self._copy_options = copy_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CopyData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CopyData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
