// <copyright file="LibraryLibraryTypeOptions.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// LibraryLibraryTypeOptions.
    /// </summary>
    /// <seealso>Emby.Api.Library.LibraryTypeOptions</seealso>
    public partial class LibraryLibraryTypeOptions :  IEquatable<LibraryLibraryTypeOptions>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryLibraryTypeOptions" /> class.
        /// </summary>
        public LibraryLibraryTypeOptions()
        {
        }
        
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        /// <value>The Type.</value>
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets MetadataFetchers
        /// </summary>
        /// <value>The MetadataFetchers.</value>
        public List<LibraryLibraryOptionInfo> MetadataFetchers { get; set; }

        /// <summary>
        /// Gets or Sets ImageFetchers
        /// </summary>
        /// <value>The ImageFetchers.</value>
        public List<LibraryLibraryOptionInfo> ImageFetchers { get; set; }

        /// <summary>
        /// Gets or Sets SupportedImageTypes
        /// </summary>
        /// <value>The SupportedImageTypes.</value>
        public List<ImageType> SupportedImageTypes { get; set; }

        /// <summary>
        /// Gets or Sets DefaultImageOptions
        /// </summary>
        /// <value>The DefaultImageOptions.</value>
        public List<ImageOption> DefaultImageOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LibraryLibraryTypeOptions {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MetadataFetchers: ").Append(MetadataFetchers).Append("\n");
            sb.Append("  ImageFetchers: ").Append(ImageFetchers).Append("\n");
            sb.Append("  SupportedImageTypes: ").Append(SupportedImageTypes).Append("\n");
            sb.Append("  DefaultImageOptions: ").Append(DefaultImageOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LibraryLibraryTypeOptions);
        }

        /// <summary>
        /// Returns true if LibraryLibraryTypeOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of LibraryLibraryTypeOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LibraryLibraryTypeOptions input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.MetadataFetchers == input.MetadataFetchers ||
                    this.MetadataFetchers != null &&
                    input.MetadataFetchers != null &&
                    this.MetadataFetchers.SequenceEqual(input.MetadataFetchers)
                ) && 
                (
                    this.ImageFetchers == input.ImageFetchers ||
                    this.ImageFetchers != null &&
                    input.ImageFetchers != null &&
                    this.ImageFetchers.SequenceEqual(input.ImageFetchers)
                ) && 
                (
                    this.SupportedImageTypes == input.SupportedImageTypes ||
                    this.SupportedImageTypes != null &&
                    input.SupportedImageTypes != null &&
                    this.SupportedImageTypes.SequenceEqual(input.SupportedImageTypes)
                ) && 
                (
                    this.DefaultImageOptions == input.DefaultImageOptions ||
                    this.DefaultImageOptions != null &&
                    input.DefaultImageOptions != null &&
                    this.DefaultImageOptions.SequenceEqual(input.DefaultImageOptions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.MetadataFetchers != null)
                    hashCode = hashCode * 59 + this.MetadataFetchers.GetHashCode();
                if (this.ImageFetchers != null)
                    hashCode = hashCode * 59 + this.ImageFetchers.GetHashCode();
                if (this.SupportedImageTypes != null)
                    hashCode = hashCode * 59 + this.SupportedImageTypes.GetHashCode();
                if (this.DefaultImageOptions != null)
                    hashCode = hashCode * 59 + this.DefaultImageOptions.GetHashCode();
                return hashCode;
            }
        }
    }
}