// <copyright file="MetadataFeatures.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines MetadataFeatures
    /// </summary>
    /// <seealso>MediaBrowser.Model.Configuration.MetadataFeatures</seealso>
    public enum MetadataFeatures
    {
        /// <summary>
        /// Enum Collections for value: Collections
        /// </summary>
        [EnumMember(Value = "Collections")]
        Collections = 1,
        /// <summary>
        /// Enum Adult for value: Adult
        /// </summary>
        [EnumMember(Value = "Adult")]
        Adult = 2,
        /// <summary>
        /// Enum RequiredSetup for value: RequiredSetup
        /// </summary>
        [EnumMember(Value = "RequiredSetup")]
        RequiredSetup = 3    }
}