// <copyright file="SeriesDisplayOrder.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines SeriesDisplayOrder
    /// </summary>
    /// <seealso>MediaBrowser.Model.Entities.SeriesDisplayOrder</seealso>
    public enum SeriesDisplayOrder
    {
        /// <summary>
        /// Enum Aired for value: Aired
        /// </summary>
        [EnumMember(Value = "Aired")]
        Aired = 1,
        /// <summary>
        /// Enum Dvd for value: Dvd
        /// </summary>
        [EnumMember(Value = "Dvd")]
        Dvd = 2,
        /// <summary>
        /// Enum Absolute for value: Absolute
        /// </summary>
        [EnumMember(Value = "Absolute")]
        Absolute = 3    }
}