// <copyright file="SubtitleLocationType.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines SubtitleLocationType
    /// </summary>
    /// <seealso>MediaBrowser.Model.Entities.SubtitleLocationType</seealso>
    public enum SubtitleLocationType
    {
        /// <summary>
        /// Enum InternalStream for value: InternalStream
        /// </summary>
        [EnumMember(Value = "InternalStream")]
        InternalStream = 1,
        /// <summary>
        /// Enum VideoSideData for value: VideoSideData
        /// </summary>
        [EnumMember(Value = "VideoSideData")]
        VideoSideData = 2    }
}