// <copyright file="SyncedItem.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// SyncedItem.
    /// </summary>
    /// <seealso>Emby.Server.Sync.Model.SyncedItem</seealso>
    public partial class SyncedItem :  IEquatable<SyncedItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncedItem" /> class.
        /// </summary>
        public SyncedItem()
        {
        }
        
        /// <summary>
        /// Gets or Sets ServerId
        /// </summary>
        /// <value>The ServerId.</value>
        public string ServerId { get; set; }

        /// <summary>
        /// Gets or Sets SyncJobId
        /// </summary>
        /// <value>The SyncJobId.</value>
        public long? SyncJobId { get; set; }

        /// <summary>
        /// Gets or Sets SyncJobName
        /// </summary>
        /// <value>The SyncJobName.</value>
        public string SyncJobName { get; set; }

        /// <summary>
        /// Gets or Sets SyncJobDateCreated
        /// </summary>
        /// <value>The SyncJobDateCreated.</value>
        public DateTimeOffset? SyncJobDateCreated { get; set; }

        /// <summary>
        /// Gets or Sets SyncJobItemId
        /// </summary>
        /// <value>The SyncJobItemId.</value>
        public long? SyncJobItemId { get; set; }

        /// <summary>
        /// Gets or Sets OriginalFileName
        /// </summary>
        /// <value>The OriginalFileName.</value>
        public string OriginalFileName { get; set; }

        /// <summary>
        /// Gets or Sets Item
        /// </summary>
        /// <value>The Item.</value>
        public BaseItemDto Item { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        /// <value>The UserId.</value>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalFiles
        /// </summary>
        /// <value>The AdditionalFiles.</value>
        public List<ItemFileInfo> AdditionalFiles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SyncedItem {\n");
            sb.Append("  ServerId: ").Append(ServerId).Append("\n");
            sb.Append("  SyncJobId: ").Append(SyncJobId).Append("\n");
            sb.Append("  SyncJobName: ").Append(SyncJobName).Append("\n");
            sb.Append("  SyncJobDateCreated: ").Append(SyncJobDateCreated).Append("\n");
            sb.Append("  SyncJobItemId: ").Append(SyncJobItemId).Append("\n");
            sb.Append("  OriginalFileName: ").Append(OriginalFileName).Append("\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AdditionalFiles: ").Append(AdditionalFiles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SyncedItem);
        }

        /// <summary>
        /// Returns true if SyncedItem instances are equal
        /// </summary>
        /// <param name="input">Instance of SyncedItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SyncedItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServerId == input.ServerId ||
                    (this.ServerId != null &&
                    this.ServerId.Equals(input.ServerId))
                ) && 
                (
                    this.SyncJobId == input.SyncJobId ||
                    (this.SyncJobId != null &&
                    this.SyncJobId.Equals(input.SyncJobId))
                ) && 
                (
                    this.SyncJobName == input.SyncJobName ||
                    (this.SyncJobName != null &&
                    this.SyncJobName.Equals(input.SyncJobName))
                ) && 
                (
                    this.SyncJobDateCreated == input.SyncJobDateCreated ||
                    (this.SyncJobDateCreated != null &&
                    this.SyncJobDateCreated.Equals(input.SyncJobDateCreated))
                ) && 
                (
                    this.SyncJobItemId == input.SyncJobItemId ||
                    (this.SyncJobItemId != null &&
                    this.SyncJobItemId.Equals(input.SyncJobItemId))
                ) && 
                (
                    this.OriginalFileName == input.OriginalFileName ||
                    (this.OriginalFileName != null &&
                    this.OriginalFileName.Equals(input.OriginalFileName))
                ) && 
                (
                    this.Item == input.Item ||
                    (this.Item != null &&
                    this.Item.Equals(input.Item))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.AdditionalFiles == input.AdditionalFiles ||
                    this.AdditionalFiles != null &&
                    input.AdditionalFiles != null &&
                    this.AdditionalFiles.SequenceEqual(input.AdditionalFiles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServerId != null)
                    hashCode = hashCode * 59 + this.ServerId.GetHashCode();
                if (this.SyncJobId != null)
                    hashCode = hashCode * 59 + this.SyncJobId.GetHashCode();
                if (this.SyncJobName != null)
                    hashCode = hashCode * 59 + this.SyncJobName.GetHashCode();
                if (this.SyncJobDateCreated != null)
                    hashCode = hashCode * 59 + this.SyncJobDateCreated.GetHashCode();
                if (this.SyncJobItemId != null)
                    hashCode = hashCode * 59 + this.SyncJobItemId.GetHashCode();
                if (this.OriginalFileName != null)
                    hashCode = hashCode * 59 + this.OriginalFileName.GetHashCode();
                if (this.Item != null)
                    hashCode = hashCode * 59 + this.Item.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.AdditionalFiles != null)
                    hashCode = hashCode * 59 + this.AdditionalFiles.GetHashCode();
                return hashCode;
            }
        }
    }
}