// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConfigurationTypeOptions
    {
        /// <summary>
        /// Initializes a new instance of the ConfigurationTypeOptions class.
        /// </summary>
        public ConfigurationTypeOptions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConfigurationTypeOptions class.
        /// </summary>
        public ConfigurationTypeOptions(string type = default(string), IList<string> metadataFetchers = default(IList<string>), IList<string> metadataFetcherOrder = default(IList<string>), IList<string> imageFetchers = default(IList<string>), IList<string> imageFetcherOrder = default(IList<string>), IList<ConfigurationImageOption> imageOptions = default(IList<ConfigurationImageOption>))
        {
            Type = type;
            MetadataFetchers = metadataFetchers;
            MetadataFetcherOrder = metadataFetcherOrder;
            ImageFetchers = imageFetchers;
            ImageFetcherOrder = imageFetcherOrder;
            ImageOptions = imageOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MetadataFetchers")]
        public IList<string> MetadataFetchers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MetadataFetcherOrder")]
        public IList<string> MetadataFetcherOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ImageFetchers")]
        public IList<string> ImageFetchers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ImageFetcherOrder")]
        public IList<string> ImageFetcherOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ImageOptions")]
        public IList<ConfigurationImageOption> ImageOptions { get; set; }

    }
}
