// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConfigurationAccessSchedule
    {
        /// <summary>
        /// Initializes a new instance of the ConfigurationAccessSchedule
        /// class.
        /// </summary>
        public ConfigurationAccessSchedule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConfigurationAccessSchedule
        /// class.
        /// </summary>
        /// <param name="dayOfWeek">Possible values include: 'Sunday',
        /// 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
        /// 'Everyday', 'Weekday', 'Weekend'</param>
        public ConfigurationAccessSchedule(string dayOfWeek = default(string), double? startHour = default(double?), double? endHour = default(double?))
        {
            DayOfWeek = dayOfWeek;
            StartHour = startHour;
            EndHour = endHour;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Sunday', 'Monday',
        /// 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
        /// 'Everyday', 'Weekday', 'Weekend'
        /// </summary>
        [JsonProperty(PropertyName = "DayOfWeek")]
        public string DayOfWeek { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartHour")]
        public double? StartHour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndHour")]
        public double? EndHour { get; set; }

    }
}
