// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmbyWebGenericUIModelUIViewInfo
    {
        /// <summary>
        /// Initializes a new instance of the EmbyWebGenericUIModelUIViewInfo
        /// class.
        /// </summary>
        public EmbyWebGenericUIModelUIViewInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmbyWebGenericUIModelUIViewInfo
        /// class.
        /// </summary>
        /// <param name="viewType">Possible values include: 'RegularPage',
        /// 'Dialog', 'Wizard'</param>
        public EmbyWebGenericUIModelUIViewInfo(string viewId = default(string), string pageId = default(string), string caption = default(string), string subCaption = default(string), string pluginId = default(string), string viewType = default(string), bool? showDialogFullScreen = default(bool?), bool? isInSequence = default(bool?), string redirectViewUrl = default(string), GenericEditIEditObjectContainer editObjectContainer = default(GenericEditIEditObjectContainer), IList<EmbyWebGenericUIModelUICommand> commands = default(IList<EmbyWebGenericUIModelUICommand>), IList<EmbyWebGenericUIModelUITabPageInfo> tabPageInfos = default(IList<EmbyWebGenericUIModelUITabPageInfo>), bool? isPageChangeInfo = default(bool?))
        {
            ViewId = viewId;
            PageId = pageId;
            Caption = caption;
            SubCaption = subCaption;
            PluginId = pluginId;
            ViewType = viewType;
            ShowDialogFullScreen = showDialogFullScreen;
            IsInSequence = isInSequence;
            RedirectViewUrl = redirectViewUrl;
            EditObjectContainer = editObjectContainer;
            Commands = commands;
            TabPageInfos = tabPageInfos;
            IsPageChangeInfo = isPageChangeInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ViewId")]
        public string ViewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PageId")]
        public string PageId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Caption")]
        public string Caption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubCaption")]
        public string SubCaption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PluginId")]
        public string PluginId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'RegularPage', 'Dialog',
        /// 'Wizard'
        /// </summary>
        [JsonProperty(PropertyName = "ViewType")]
        public string ViewType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ShowDialogFullScreen")]
        public bool? ShowDialogFullScreen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsInSequence")]
        public bool? IsInSequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RedirectViewUrl")]
        public string RedirectViewUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EditObjectContainer")]
        public GenericEditIEditObjectContainer EditObjectContainer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Commands")]
        public IList<EmbyWebGenericUIModelUICommand> Commands { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TabPageInfos")]
        public IList<EmbyWebGenericUIModelUITabPageInfo> TabPageInfos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPageChangeInfo")]
        public bool? IsPageChangeInfo { get; set; }

    }
}
