// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmbyWebGenericEditEditObjectContainer
    {
        /// <summary>
        /// Initializes a new instance of the
        /// EmbyWebGenericEditEditObjectContainer class.
        /// </summary>
        public EmbyWebGenericEditEditObjectContainer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// EmbyWebGenericEditEditObjectContainer class.
        /// </summary>
        public EmbyWebGenericEditEditObjectContainer(object objectProperty = default(object), object defaultObject = default(object), string typeName = default(string), EmbyWebGenericEditEditorsEditorRoot editorRoot = default(EmbyWebGenericEditEditorsEditorRoot))
        {
            ObjectProperty = objectProperty;
            DefaultObject = defaultObject;
            TypeName = typeName;
            EditorRoot = editorRoot;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Object")]
        public object ObjectProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DefaultObject")]
        public object DefaultObject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeName")]
        public string TypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EditorRoot")]
        public EmbyWebGenericEditEditorsEditorRoot EditorRoot { get; set; }

    }
}
