// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LibraryLibraryOptionsResult
    {
        /// <summary>
        /// Initializes a new instance of the LibraryLibraryOptionsResult
        /// class.
        /// </summary>
        public LibraryLibraryOptionsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LibraryLibraryOptionsResult
        /// class.
        /// </summary>
        public LibraryLibraryOptionsResult(IList<LibraryLibraryOptionInfo> metadataSavers = default(IList<LibraryLibraryOptionInfo>), IList<LibraryLibraryOptionInfo> metadataReaders = default(IList<LibraryLibraryOptionInfo>), IList<LibraryLibraryOptionInfo> subtitleFetchers = default(IList<LibraryLibraryOptionInfo>), IList<LibraryLibraryOptionInfo> lyricsFetchers = default(IList<LibraryLibraryOptionInfo>), IList<LibraryLibraryTypeOptions> typeOptions = default(IList<LibraryLibraryTypeOptions>))
        {
            MetadataSavers = metadataSavers;
            MetadataReaders = metadataReaders;
            SubtitleFetchers = subtitleFetchers;
            LyricsFetchers = lyricsFetchers;
            TypeOptions = typeOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MetadataSavers")]
        public IList<LibraryLibraryOptionInfo> MetadataSavers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MetadataReaders")]
        public IList<LibraryLibraryOptionInfo> MetadataReaders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubtitleFetchers")]
        public IList<LibraryLibraryOptionInfo> SubtitleFetchers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LyricsFetchers")]
        public IList<LibraryLibraryOptionInfo> LyricsFetchers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeOptions")]
        public IList<LibraryLibraryTypeOptions> TypeOptions { get; set; }

    }
}
