// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LibraryMediaFolder
    {
        /// <summary>
        /// Initializes a new instance of the LibraryMediaFolder class.
        /// </summary>
        public LibraryMediaFolder()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LibraryMediaFolder class.
        /// </summary>
        public LibraryMediaFolder(string name = default(string), string id = default(string), string guid = default(string), IList<LibrarySubFolder> subFolders = default(IList<LibrarySubFolder>))
        {
            Name = name;
            Id = id;
            Guid = guid;
            SubFolders = subFolders;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Guid")]
        public string Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubFolders")]
        public IList<LibrarySubFolder> SubFolders { get; set; }

    }
}
