// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LibraryRemoveMediaPath
    {
        /// <summary>
        /// Initializes a new instance of the LibraryRemoveMediaPath class.
        /// </summary>
        public LibraryRemoveMediaPath()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LibraryRemoveMediaPath class.
        /// </summary>
        public LibraryRemoveMediaPath(string id = default(string), string path = default(string), bool? refreshLibrary = default(bool?))
        {
            Id = id;
            Path = path;
            RefreshLibrary = refreshLibrary;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RefreshLibrary")]
        public bool? RefreshLibrary { get; set; }

    }
}
