// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MediaInfoLiveStreamRequest
    {
        /// <summary>
        /// Initializes a new instance of the MediaInfoLiveStreamRequest class.
        /// </summary>
        public MediaInfoLiveStreamRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MediaInfoLiveStreamRequest class.
        /// </summary>
        public MediaInfoLiveStreamRequest(string openToken = default(string), string userId = default(string), string playSessionId = default(string), long? maxStreamingBitrate = default(long?), long? startTimeTicks = default(long?), int? audioStreamIndex = default(int?), int? subtitleStreamIndex = default(int?), int? maxAudioChannels = default(int?), long? itemId = default(long?), DlnaDeviceProfile deviceProfile = default(DlnaDeviceProfile), bool? enableDirectPlay = default(bool?), bool? enableDirectStream = default(bool?), bool? enableTranscoding = default(bool?), bool? allowVideoStreamCopy = default(bool?), bool? allowInterlacedVideoStreamCopy = default(bool?), bool? allowAudioStreamCopy = default(bool?), IList<string> directPlayProtocols = default(IList<string>))
        {
            OpenToken = openToken;
            UserId = userId;
            PlaySessionId = playSessionId;
            MaxStreamingBitrate = maxStreamingBitrate;
            StartTimeTicks = startTimeTicks;
            AudioStreamIndex = audioStreamIndex;
            SubtitleStreamIndex = subtitleStreamIndex;
            MaxAudioChannels = maxAudioChannels;
            ItemId = itemId;
            DeviceProfile = deviceProfile;
            EnableDirectPlay = enableDirectPlay;
            EnableDirectStream = enableDirectStream;
            EnableTranscoding = enableTranscoding;
            AllowVideoStreamCopy = allowVideoStreamCopy;
            AllowInterlacedVideoStreamCopy = allowInterlacedVideoStreamCopy;
            AllowAudioStreamCopy = allowAudioStreamCopy;
            DirectPlayProtocols = directPlayProtocols;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OpenToken")]
        public string OpenToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PlaySessionId")]
        public string PlaySessionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxStreamingBitrate")]
        public long? MaxStreamingBitrate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTimeTicks")]
        public long? StartTimeTicks { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AudioStreamIndex")]
        public int? AudioStreamIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubtitleStreamIndex")]
        public int? SubtitleStreamIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxAudioChannels")]
        public int? MaxAudioChannels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ItemId")]
        public long? ItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeviceProfile")]
        public DlnaDeviceProfile DeviceProfile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnableDirectPlay")]
        public bool? EnableDirectPlay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnableDirectStream")]
        public bool? EnableDirectStream { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnableTranscoding")]
        public bool? EnableTranscoding { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllowVideoStreamCopy")]
        public bool? AllowVideoStreamCopy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllowInterlacedVideoStreamCopy")]
        public bool? AllowInterlacedVideoStreamCopy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllowAudioStreamCopy")]
        public bool? AllowAudioStreamCopy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DirectPlayProtocols")]
        public IList<string> DirectPlayProtocols { get; set; }

    }
}
