// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RemoteSubtitleInfo
    {
        /// <summary>
        /// Initializes a new instance of the RemoteSubtitleInfo class.
        /// </summary>
        public RemoteSubtitleInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RemoteSubtitleInfo class.
        /// </summary>
        public RemoteSubtitleInfo(string threeLetterISOLanguageName = default(string), string id = default(string), string providerName = default(string), string name = default(string), string format = default(string), string author = default(string), string comment = default(string), System.DateTime? dateCreated = default(System.DateTime?), double? communityRating = default(double?), int? downloadCount = default(int?), bool? isHashMatch = default(bool?), bool? isForced = default(bool?), string language = default(string))
        {
            ThreeLetterISOLanguageName = threeLetterISOLanguageName;
            Id = id;
            ProviderName = providerName;
            Name = name;
            Format = format;
            Author = author;
            Comment = comment;
            DateCreated = dateCreated;
            CommunityRating = communityRating;
            DownloadCount = downloadCount;
            IsHashMatch = isHashMatch;
            IsForced = isForced;
            Language = language;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ThreeLetterISOLanguageName")]
        public string ThreeLetterISOLanguageName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProviderName")]
        public string ProviderName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Format")]
        public string Format { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Comment")]
        public string Comment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CommunityRating")]
        public double? CommunityRating { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DownloadCount")]
        public int? DownloadCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsHashMatch")]
        public bool? IsHashMatch { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsForced")]
        public bool? IsForced { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Language")]
        public string Language { get; set; }

    }
}
