// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SessionUserInfo
    {
        /// <summary>
        /// Initializes a new instance of the SessionUserInfo class.
        /// </summary>
        public SessionUserInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SessionUserInfo class.
        /// </summary>
        public SessionUserInfo(string userId = default(string), string userName = default(string), long? userInternalId = default(long?))
        {
            UserId = userId;
            UserName = userName;
            UserInternalId = userInternalId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserInternalId")]
        public long? UserInternalId { get; set; }

    }
}
