// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EmbyClient.MsRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubtitlesSubtitleDownloadResult
    {
        /// <summary>
        /// Initializes a new instance of the SubtitlesSubtitleDownloadResult
        /// class.
        /// </summary>
        public SubtitlesSubtitleDownloadResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubtitlesSubtitleDownloadResult
        /// class.
        /// </summary>
        public SubtitlesSubtitleDownloadResult(int? newIndex = default(int?))
        {
            NewIndex = newIndex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NewIndex")]
        public int? NewIndex { get; set; }

    }
}
