// <copyright file="EmbyKnownTokenAuthenticator.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>

namespace Emby.ApiClient.Client.Authentication
{
    using RestSharp;
    using RestSharp.Authenticators;
    using System;
    using System.Threading.Tasks;

    /// <summary>
    /// Emby Authenticator for cases when the access token is already known.
    /// </summary>
    /// <remarks>See https://dev.emby.media/doc/restapi/User-Authentication.html.</remarks>
    public class EmbyKnownTokenAuthenticator : IEmbyAuthenticator
    {
        public EmbyKnownTokenAuthenticator(EmbyAuthInfo authInfo, string token)
        : this(authInfo)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(token));
            }

            this.Token = token;
        }

        protected EmbyKnownTokenAuthenticator(EmbyAuthInfo authInfo)
        {
            if (authInfo == null)
            {
                throw new ArgumentNullException(nameof(authInfo));
            }

            this.AuthInfo = authInfo;
        }

        public EmbyAuthInfo AuthInfo { get; }

        public virtual string Token { get; }

        protected virtual ValueTask<Parameter> GetAuthenticationParameter()
        {
            var paramValue = this.AuthInfo.ToString(this.Token);
            var paramter = new HeaderParameter(KnownHeaders.Authorization, paramValue);

            return new ValueTask<Parameter>(paramter);
        }

        public virtual async ValueTask Authenticate(IRestClient client, RestRequest request)
        {
            request.AddOrUpdateParameter(await this.GetAuthenticationParameter().ConfigureAwait(false));
        }
    }
}
