/*
 * Emby Server REST API (BETA)
 *
 * Explore the Emby Server API
 *
 */
package embyclient-rest-go

type EmbyWebGenericEditCommonEditorTypes string

// List of Emby.Web.GenericEdit.Common.EditorTypes
const (
	GROUP_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "Group"
	TEXT_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "Text"
	NUMERIC_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "Numeric"
	BOOLEAN_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "Boolean"
	SELECT_SINGLE_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "SelectSingle"
	SELECT_MULTIPLE_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "SelectMultiple"
	DATE_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "Date"
	FILE_PATH_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "FilePath"
	FOLDER_PATH_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "FolderPath"
	STATUS_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "StatusItem"
	PROGRESS_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "ProgressItem"
	BUTTON_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "ButtonItem"
	BUTTON_GROUP_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "ButtonGroup"
	CAPTION_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "CaptionItem"
	LABEL_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "LabelItem"
	ITEM_LIST_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "ItemList"
	RADIO_GROUP_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "RadioGroup"
	DATA_GRID_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "DataGrid"
	PIVOT_GRID_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "PivotGrid"
	SPACER_ITEM_EmbyWebGenericEditCommonEditorTypes EmbyWebGenericEditCommonEditorTypes = "SpacerItem"
)
