/*
 * Emby Server REST API (BETA)
 *
 * Explore the Emby Server API
 *
 * API version: 4.8.0.3
 */
package embyclient-rest-go
import (
	"time"
)

type BaseItemDto struct {
	Name string `json:"Name,omitempty"`
	OriginalTitle string `json:"OriginalTitle,omitempty"`
	ServerId string `json:"ServerId,omitempty"`
	Id string `json:"Id,omitempty"`
	Guid string `json:"Guid,omitempty"`
	Etag string `json:"Etag,omitempty"`
	Prefix string `json:"Prefix,omitempty"`
	PlaylistItemId string `json:"PlaylistItemId,omitempty"`
	DateCreated time.Time `json:"DateCreated,omitempty"`
	ExtraType string `json:"ExtraType,omitempty"`
	SortIndexNumber int32 `json:"SortIndexNumber,omitempty"`
	SortParentIndexNumber int32 `json:"SortParentIndexNumber,omitempty"`
	AirsBeforeSeasonNumber int32 `json:"AirsBeforeSeasonNumber,omitempty"`
	AirsAfterSeasonNumber int32 `json:"AirsAfterSeasonNumber,omitempty"`
	AirsBeforeEpisodeNumber int32 `json:"AirsBeforeEpisodeNumber,omitempty"`
	CanDelete bool `json:"CanDelete,omitempty"`
	CanDownload bool `json:"CanDownload,omitempty"`
	SupportsResume bool `json:"SupportsResume,omitempty"`
	PresentationUniqueKey string `json:"PresentationUniqueKey,omitempty"`
	PreferredMetadataLanguage string `json:"PreferredMetadataLanguage,omitempty"`
	PreferredMetadataCountryCode string `json:"PreferredMetadataCountryCode,omitempty"`
	SupportsSync bool `json:"SupportsSync,omitempty"`
	Container string `json:"Container,omitempty"`
	SortName string `json:"SortName,omitempty"`
	ForcedSortName string `json:"ForcedSortName,omitempty"`
	Video3DFormat *Video3DFormat `json:"Video3DFormat,omitempty"`
	PremiereDate time.Time `json:"PremiereDate,omitempty"`
	ExternalUrls []ExternalUrl `json:"ExternalUrls,omitempty"`
	MediaSources []MediaSourceInfo `json:"MediaSources,omitempty"`
	CriticRating float32 `json:"CriticRating,omitempty"`
	GameSystemId int64 `json:"GameSystemId,omitempty"`
	AsSeries bool `json:"AsSeries,omitempty"`
	GameSystem string `json:"GameSystem,omitempty"`
	ProductionLocations []string `json:"ProductionLocations,omitempty"`
	Path string `json:"Path,omitempty"`
	OfficialRating string `json:"OfficialRating,omitempty"`
	CustomRating string `json:"CustomRating,omitempty"`
	ChannelId string `json:"ChannelId,omitempty"`
	ChannelName string `json:"ChannelName,omitempty"`
	Overview string `json:"Overview,omitempty"`
	Taglines []string `json:"Taglines,omitempty"`
	Genres []string `json:"Genres,omitempty"`
	CommunityRating float32 `json:"CommunityRating,omitempty"`
	RunTimeTicks int64 `json:"RunTimeTicks,omitempty"`
	Size int64 `json:"Size,omitempty"`
	FileName string `json:"FileName,omitempty"`
	Bitrate int32 `json:"Bitrate,omitempty"`
	PlayAccess *LibraryPlayAccess `json:"PlayAccess,omitempty"`
	ProductionYear int32 `json:"ProductionYear,omitempty"`
	Number string `json:"Number,omitempty"`
	ChannelNumber string `json:"ChannelNumber,omitempty"`
	IndexNumber int32 `json:"IndexNumber,omitempty"`
	IndexNumberEnd int32 `json:"IndexNumberEnd,omitempty"`
	ParentIndexNumber int32 `json:"ParentIndexNumber,omitempty"`
	RemoteTrailers []MediaUrl `json:"RemoteTrailers,omitempty"`
	ProviderIds *map[string]string `json:"ProviderIds,omitempty"`
	IsFolder bool `json:"IsFolder,omitempty"`
	ParentId string `json:"ParentId,omitempty"`
	Type_ string `json:"Type,omitempty"`
	People []BaseItemPerson `json:"People,omitempty"`
	Studios []NameLongIdPair `json:"Studios,omitempty"`
	GenreItems []NameLongIdPair `json:"GenreItems,omitempty"`
	TagItems []NameLongIdPair `json:"TagItems,omitempty"`
	ParentLogoItemId string `json:"ParentLogoItemId,omitempty"`
	ParentBackdropItemId string `json:"ParentBackdropItemId,omitempty"`
	ParentBackdropImageTags []string `json:"ParentBackdropImageTags,omitempty"`
	LocalTrailerCount int32 `json:"LocalTrailerCount,omitempty"`
	UserData *UserItemDataDto `json:"UserData,omitempty"`
	RecursiveItemCount int32 `json:"RecursiveItemCount,omitempty"`
	ChildCount int32 `json:"ChildCount,omitempty"`
	SeriesName string `json:"SeriesName,omitempty"`
	SeriesId string `json:"SeriesId,omitempty"`
	SeasonId string `json:"SeasonId,omitempty"`
	SpecialFeatureCount int32 `json:"SpecialFeatureCount,omitempty"`
	DisplayPreferencesId string `json:"DisplayPreferencesId,omitempty"`
	Status string `json:"Status,omitempty"`
	AirDays []DayOfWeek `json:"AirDays,omitempty"`
	Tags []string `json:"Tags,omitempty"`
	PrimaryImageAspectRatio float64 `json:"PrimaryImageAspectRatio,omitempty"`
	Artists []string `json:"Artists,omitempty"`
	ArtistItems []NameIdPair `json:"ArtistItems,omitempty"`
	Composers []NameIdPair `json:"Composers,omitempty"`
	Album string `json:"Album,omitempty"`
	CollectionType string `json:"CollectionType,omitempty"`
	DisplayOrder string `json:"DisplayOrder,omitempty"`
	AlbumId string `json:"AlbumId,omitempty"`
	AlbumPrimaryImageTag string `json:"AlbumPrimaryImageTag,omitempty"`
	SeriesPrimaryImageTag string `json:"SeriesPrimaryImageTag,omitempty"`
	AlbumArtist string `json:"AlbumArtist,omitempty"`
	AlbumArtists []NameIdPair `json:"AlbumArtists,omitempty"`
	SeasonName string `json:"SeasonName,omitempty"`
	MediaStreams []MediaStream `json:"MediaStreams,omitempty"`
	PartCount int32 `json:"PartCount,omitempty"`
	ImageTags map[string]string `json:"ImageTags,omitempty"`
	BackdropImageTags []string `json:"BackdropImageTags,omitempty"`
	ParentLogoImageTag string `json:"ParentLogoImageTag,omitempty"`
	SeriesStudio string `json:"SeriesStudio,omitempty"`
	ParentThumbItemId string `json:"ParentThumbItemId,omitempty"`
	ParentThumbImageTag string `json:"ParentThumbImageTag,omitempty"`
	Chapters []ChapterInfo `json:"Chapters,omitempty"`
	LocationType *LocationType `json:"LocationType,omitempty"`
	MediaType string `json:"MediaType,omitempty"`
	EndDate time.Time `json:"EndDate,omitempty"`
	LockedFields []MetadataFields `json:"LockedFields,omitempty"`
	LockData bool `json:"LockData,omitempty"`
	Width int32 `json:"Width,omitempty"`
	Height int32 `json:"Height,omitempty"`
	CameraMake string `json:"CameraMake,omitempty"`
	CameraModel string `json:"CameraModel,omitempty"`
	Software string `json:"Software,omitempty"`
	ExposureTime float64 `json:"ExposureTime,omitempty"`
	FocalLength float64 `json:"FocalLength,omitempty"`
	ImageOrientation *DrawingImageOrientation `json:"ImageOrientation,omitempty"`
	Aperture float64 `json:"Aperture,omitempty"`
	ShutterSpeed float64 `json:"ShutterSpeed,omitempty"`
	Latitude float64 `json:"Latitude,omitempty"`
	Longitude float64 `json:"Longitude,omitempty"`
	Altitude float64 `json:"Altitude,omitempty"`
	IsoSpeedRating int32 `json:"IsoSpeedRating,omitempty"`
	SeriesTimerId string `json:"SeriesTimerId,omitempty"`
	ChannelPrimaryImageTag string `json:"ChannelPrimaryImageTag,omitempty"`
	StartDate time.Time `json:"StartDate,omitempty"`
	CompletionPercentage float64 `json:"CompletionPercentage,omitempty"`
	IsRepeat bool `json:"IsRepeat,omitempty"`
	IsNew bool `json:"IsNew,omitempty"`
	EpisodeTitle string `json:"EpisodeTitle,omitempty"`
	IsMovie bool `json:"IsMovie,omitempty"`
	IsSports bool `json:"IsSports,omitempty"`
	IsSeries bool `json:"IsSeries,omitempty"`
	IsLive bool `json:"IsLive,omitempty"`
	IsNews bool `json:"IsNews,omitempty"`
	IsKids bool `json:"IsKids,omitempty"`
	IsPremiere bool `json:"IsPremiere,omitempty"`
	TimerType *LiveTvTimerType `json:"TimerType,omitempty"`
	Disabled bool `json:"Disabled,omitempty"`
	ManagementId string `json:"ManagementId,omitempty"`
	TimerId string `json:"TimerId,omitempty"`
	CurrentProgram *BaseItemDto `json:"CurrentProgram,omitempty"`
	MovieCount int32 `json:"MovieCount,omitempty"`
	SeriesCount int32 `json:"SeriesCount,omitempty"`
	AlbumCount int32 `json:"AlbumCount,omitempty"`
	SongCount int32 `json:"SongCount,omitempty"`
	MusicVideoCount int32 `json:"MusicVideoCount,omitempty"`
	Subviews []string `json:"Subviews,omitempty"`
	ListingsProviderId string `json:"ListingsProviderId,omitempty"`
	ListingsChannelId string `json:"ListingsChannelId,omitempty"`
	ListingsPath string `json:"ListingsPath,omitempty"`
	ListingsId string `json:"ListingsId,omitempty"`
	ListingsChannelName string `json:"ListingsChannelName,omitempty"`
	ListingsChannelNumber string `json:"ListingsChannelNumber,omitempty"`
	AffiliateCallSign string `json:"AffiliateCallSign,omitempty"`
}
