/*
 * Emby Server REST API (BETA)
 *
 * Explore the Emby Server API
 *
 */
package embyclient-rest-go

type EmbyWebGenericUiModelEnumsUiCommandType string

// List of Emby.Web.GenericUI.Model.Enums.UICommandType
const (
	CUSTOM_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "Custom"
	WIZARD_CANCEL_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardCancel"
	WIZARD_BACK_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardBack"
	WIZARD_NEXT_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardNext"
	WIZARD_FINISH_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardFinish"
	DIALOG_CANCEL_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "DialogCancel"
	DIALOG_OK_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "DialogOk"
	PAGE_SAVE_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "PageSave"
	PAGE_BACK_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "PageBack"
	WIZARD_BUTTON1_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardButton1"
	WIZARD_BUTTON2_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardButton2"
	WIZARD_BUTTON3_EmbyWebGenericUiModelEnumsUiCommandType EmbyWebGenericUiModelEnumsUiCommandType = "WizardButton3"
)
