//
// MetadataRefreshMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum MetadataRefreshMode: String, Codable {
    case validationOnly = "ValidationOnly"
    case _default = "Default"
    case fullRefresh = "FullRefresh"
}