//
// RecommendationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RecommendationDto: Codable {

    public var items: [BaseItemDto]?
    public var recommendationType: RecommendationType?
    public var baselineItemName: String?
    public var categoryId: Int64?

    public init(items: [BaseItemDto]? = nil, recommendationType: RecommendationType? = nil, baselineItemName: String? = nil, categoryId: Int64? = nil) {
        self.items = items
        self.recommendationType = recommendationType
        self.baselineItemName = baselineItemName
        self.categoryId = categoryId
    }

    public enum CodingKeys: String, CodingKey { 
        case items = "Items"
        case recommendationType = "RecommendationType"
        case baselineItemName = "BaselineItemName"
        case categoryId = "CategoryId"
    }

}
