//
// RokuMetadataApiThumbnailSetInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RokuMetadataApiThumbnailSetInfo: Codable {

    public var aspectRatio: Double?
    public var thumbnails: [RokuMetadataApiThumbnailInfo]?

    public init(aspectRatio: Double? = nil, thumbnails: [RokuMetadataApiThumbnailInfo]? = nil) {
        self.aspectRatio = aspectRatio
        self.thumbnails = thumbnails
    }

    public enum CodingKeys: String, CodingKey { 
        case aspectRatio = "AspectRatio"
        case thumbnails = "Thumbnails"
    }

}
