//
// SeriesInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SeriesInfo: Codable {

    public var episodeAirDate: Date?
    public var displayOrder: SeriesDisplayOrder?
    /** The name. */
    public var name: String?
    public var path: String?
    /** The metadata language. */
    public var metadataLanguage: String?
    /** The metadata country code. */
    public var metadataCountryCode: String?
    public var metadataLanguages: [GlobalizationCultureDto]?
    public var providerIds: ProviderIdDictionary?
    /** The year. */
    public var year: Int?
    public var indexNumber: Int?
    public var parentIndexNumber: Int?
    public var premiereDate: Date?
    public var isAutomated: Bool?
    public var enableAdultMetadata: Bool?

    public init(episodeAirDate: Date? = nil, displayOrder: SeriesDisplayOrder? = nil, name: String? = nil, path: String? = nil, metadataLanguage: String? = nil, metadataCountryCode: String? = nil, metadataLanguages: [GlobalizationCultureDto]? = nil, providerIds: ProviderIdDictionary? = nil, year: Int? = nil, indexNumber: Int? = nil, parentIndexNumber: Int? = nil, premiereDate: Date? = nil, isAutomated: Bool? = nil, enableAdultMetadata: Bool? = nil) {
        self.episodeAirDate = episodeAirDate
        self.displayOrder = displayOrder
        self.name = name
        self.path = path
        self.metadataLanguage = metadataLanguage
        self.metadataCountryCode = metadataCountryCode
        self.metadataLanguages = metadataLanguages
        self.providerIds = providerIds
        self.year = year
        self.indexNumber = indexNumber
        self.parentIndexNumber = parentIndexNumber
        self.premiereDate = premiereDate
        self.isAutomated = isAutomated
        self.enableAdultMetadata = enableAdultMetadata
    }

    public enum CodingKeys: String, CodingKey { 
        case episodeAirDate = "EpisodeAirDate"
        case displayOrder = "DisplayOrder"
        case name = "Name"
        case path = "Path"
        case metadataLanguage = "MetadataLanguage"
        case metadataCountryCode = "MetadataCountryCode"
        case metadataLanguages = "MetadataLanguages"
        case providerIds = "ProviderIds"
        case year = "Year"
        case indexNumber = "IndexNumber"
        case parentIndexNumber = "ParentIndexNumber"
        case premiereDate = "PremiereDate"
        case isAutomated = "IsAutomated"
        case enableAdultMetadata = "EnableAdultMetadata"
    }

}
