//
// BitRate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A type for handling bit rates.      The purpose of this type is to avoid manual calculations and conversions in code,             unified handling and conversion as well as presentation through its various To\\*\\*\\*String methods.      &#x60;System.IComparable&#x60;      &#x60;System.IEquatable&#x60;1&#x60;   */

public struct BitRate: Codable {

    public var bps: Int64?
    public var kbps: Double?
    public var mbps: Double?

    public init(bps: Int64? = nil, kbps: Double? = nil, mbps: Double? = nil) {
        self.bps = bps
        self.kbps = kbps
        self.mbps = mbps
    }

    public enum CodingKeys: String, CodingKey { 
        case bps
        case kbps
        case mbps = "Mbps"
    }

}
