//
// EmbyMediaModelTypesResolution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmbyMediaModelTypesResolution: Codable {

    public var width: Int?
    public var height: Int?

    public init(width: Int? = nil, height: Int? = nil) {
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey { 
        case width = "Width"
        case height = "Height"
    }

}
