//
// EmbyFeaturesFeatureInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmbyFeaturesFeatureInfo: Codable {

    public var name: String?
    public var _id: String?
    public var featureType: EmbyFeaturesFeatureType?

    public init(name: String? = nil, _id: String? = nil, featureType: EmbyFeaturesFeatureType? = nil) {
        self.name = name
        self._id = _id
        self.featureType = featureType
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _id = "Id"
        case featureType = "FeatureType"
    }

}
