//
// SyncDialogOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SyncDialogOptions: Codable {

    public var targets: [SyncTarget]?
    public var options: [SyncJobOption]?
    public var qualityOptions: [SyncQualityOption]?
    public var profileOptions: [SyncProfileOption]?

    public init(targets: [SyncTarget]? = nil, options: [SyncJobOption]? = nil, qualityOptions: [SyncQualityOption]? = nil, profileOptions: [SyncProfileOption]? = nil) {
        self.targets = targets
        self.options = options
        self.qualityOptions = qualityOptions
        self.profileOptions = profileOptions
    }

    public enum CodingKeys: String, CodingKey { 
        case targets = "Targets"
        case options = "Options"
        case qualityOptions = "QualityOptions"
        case profileOptions = "ProfileOptions"
    }

}
