//
// NotificationsApiAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class NotificationsApiAPI {
    /**
     Gets notification types

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getNotificationsAll(completion: @escaping ((_ data: [EmbyNotificationsNotificationCategoryInfo]?,_ error: Error?) -> Void)) {
        getNotificationsAllWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Gets notification types
     - GET /Notifications/All

     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apikeyauth
     - :
       - type: http
       - name: embyauth
     - examples: [{contentType=application/json, example=[ {
  "Events" : [ {
    "CategoryId" : "CategoryId",
    "CategoryName" : "CategoryName",
    "Id" : "Id",
    "Name" : "Name"
  }, {
    "CategoryId" : "CategoryId",
    "CategoryName" : "CategoryName",
    "Id" : "Id",
    "Name" : "Name"
  } ],
  "Id" : "Id",
  "Name" : "Name"
}, {
  "Events" : [ {
    "CategoryId" : "CategoryId",
    "CategoryName" : "CategoryName",
    "Id" : "Id",
    "Name" : "Name"
  }, {
    "CategoryId" : "CategoryId",
    "CategoryName" : "CategoryName",
    "Id" : "Id",
    "Name" : "Name"
  } ],
  "Id" : "Id",
  "Name" : "Name"
} ]}]

     - returns: RequestBuilder<[EmbyNotificationsNotificationCategoryInfo]> 
     */
    open class func getNotificationsAllWithRequestBuilder() -> RequestBuilder<[EmbyNotificationsNotificationCategoryInfo]> {
        let path = "/Notifications/All"
        let URLString = embyclient-rest-swift-betaAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[EmbyNotificationsNotificationCategoryInfo]>.Type = embyclient-rest-swift-betaAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
