//
// VideoHlsServiceAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class VideoHlsServiceAPI {
    /**

     - parameter segmentContainer: (path)  
     - parameter segmentId: (path)  
     - parameter _id: (path)  
     - parameter playlistId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVideosByIdHlsByPlaylistidBySegmentidBySegmentcontainer(segmentContainer: String, segmentId: String, _id: String, playlistId: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        getVideosByIdHlsByPlaylistidBySegmentidBySegmentcontainerWithRequestBuilder(segmentContainer: segmentContainer, segmentId: segmentId, _id: _id, playlistId: playlistId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /Videos/{Id}/hls/{PlaylistId}/{SegmentId}.{SegmentContainer}

     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apikeyauth
     - :
       - type: http
       - name: embyauth
     - parameter segmentContainer: (path)  
     - parameter segmentId: (path)  
     - parameter _id: (path)  
     - parameter playlistId: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func getVideosByIdHlsByPlaylistidBySegmentidBySegmentcontainerWithRequestBuilder(segmentContainer: String, segmentId: String, _id: String, playlistId: String) -> RequestBuilder<Void> {
        var path = "/Videos/{Id}/hls/{PlaylistId}/{SegmentId}.{SegmentContainer}"
        let segmentContainerPreEscape = "\(segmentContainer)"
        let segmentContainerPostEscape = segmentContainerPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{SegmentContainer}", with: segmentContainerPostEscape, options: .literal, range: nil)
        let segmentIdPreEscape = "\(segmentId)"
        let segmentIdPostEscape = segmentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{SegmentId}", with: segmentIdPostEscape, options: .literal, range: nil)
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{Id}", with: _idPostEscape, options: .literal, range: nil)
        let playlistIdPreEscape = "\(playlistId)"
        let playlistIdPostEscape = playlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{PlaylistId}", with: playlistIdPostEscape, options: .literal, range: nil)
        let URLString = embyclient-rest-swift-betaAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = embyclient-rest-swift-betaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path) Item Id 
     - parameter container: (query) Container 
     - parameter deviceProfileId: (query) Optional. The dlna device profile id to utilize. (optional)
     - parameter deviceId: (query) The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     - parameter audioCodec: (query) Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#x27;s extension. Options: aac, mp3, vorbis, wma. (optional)
     - parameter enableAutoStreamCopy: (query) Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true. (optional)
     - parameter audioSampleRate: (query) Optional. Specify a specific audio sample rate, e.g. 44100 (optional)
     - parameter audioBitRate: (query) Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     - parameter audioChannels: (query) Optional. Specify a specific number of audio channels to encode to, e.g. 2 (optional)
     - parameter maxAudioChannels: (query) Optional. Specify a maximum number of audio channels to encode to, e.g. 2 (optional)
     - parameter _static: (query) Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false (optional)
     - parameter profile: (query) Optional. Specify a specific h264 profile, e.g. main, baseline, high. (optional)
     - parameter level: (query) Optional. Specify a level for the h264 profile, e.g. 3, 3.1. (optional)
     - parameter framerate: (query) Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements. (optional)
     - parameter maxFramerate: (query) Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements. (optional)
     - parameter copyTimestamps: (query) Whether or not to copy timestamps when transcoding with an offset. Defaults to false. (optional)
     - parameter startTimeTicks: (query) Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks. (optional)
     - parameter width: (query) Optional. The fixed horizontal resolution of the encoded video. (optional)
     - parameter height: (query) Optional. The fixed vertical resolution of the encoded video. (optional)
     - parameter maxWidth: (query) Optional. The maximum horizontal resolution of the encoded video. (optional)
     - parameter maxHeight: (query) Optional. The maximum vertical resolution of the encoded video. (optional)
     - parameter videoBitRate: (query) Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults. (optional)
     - parameter subtitleStreamIndex: (query) Optional. The index of the subtitle stream to use. If omitted no subtitles will be used. (optional)
     - parameter subtitleMethod: (query) Optional. Specify the subtitle delivery method. (optional)
     - parameter maxRefFrames: (query) Optional. (optional)
     - parameter maxVideoBitDepth: (query) Optional. (optional)
     - parameter videoCodec: (query) Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#x27;s extension. Options: h264, mpeg4, theora, vpx, wmv. (optional)
     - parameter audioStreamIndex: (query) Optional. The index of the audio stream to use. If omitted the first audio stream will be used. (optional)
     - parameter videoStreamIndex: (query) Optional. The index of the video stream to use. If omitted the first video stream will be used. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVideosByIdLiveM3u8(_id: String, container: String, deviceProfileId: String? = nil, deviceId: String? = nil, audioCodec: String? = nil, enableAutoStreamCopy: Bool? = nil, audioSampleRate: Int? = nil, audioBitRate: Int? = nil, audioChannels: Int? = nil, maxAudioChannels: Int? = nil, _static: Bool? = nil, profile: String? = nil, level: String? = nil, framerate: Float? = nil, maxFramerate: Float? = nil, copyTimestamps: Bool? = nil, startTimeTicks: Int64? = nil, width: Int? = nil, height: Int? = nil, maxWidth: Int? = nil, maxHeight: Int? = nil, videoBitRate: Int? = nil, subtitleStreamIndex: Int? = nil, subtitleMethod: SubtitleDeliveryMethod? = nil, maxRefFrames: Int? = nil, maxVideoBitDepth: Int? = nil, videoCodec: String? = nil, audioStreamIndex: Int? = nil, videoStreamIndex: Int? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        getVideosByIdLiveM3u8WithRequestBuilder(_id: _id, container: container, deviceProfileId: deviceProfileId, deviceId: deviceId, audioCodec: audioCodec, enableAutoStreamCopy: enableAutoStreamCopy, audioSampleRate: audioSampleRate, audioBitRate: audioBitRate, audioChannels: audioChannels, maxAudioChannels: maxAudioChannels, _static: _static, profile: profile, level: level, framerate: framerate, maxFramerate: maxFramerate, copyTimestamps: copyTimestamps, startTimeTicks: startTimeTicks, width: width, height: height, maxWidth: maxWidth, maxHeight: maxHeight, videoBitRate: videoBitRate, subtitleStreamIndex: subtitleStreamIndex, subtitleMethod: subtitleMethod, maxRefFrames: maxRefFrames, maxVideoBitDepth: maxVideoBitDepth, videoCodec: videoCodec, audioStreamIndex: audioStreamIndex, videoStreamIndex: videoStreamIndex).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /Videos/{Id}/live.m3u8

     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apikeyauth
     - :
       - type: http
       - name: embyauth
     - parameter _id: (path) Item Id 
     - parameter container: (query) Container 
     - parameter deviceProfileId: (query) Optional. The dlna device profile id to utilize. (optional)
     - parameter deviceId: (query) The device id of the client requesting. Used to stop encoding processes when needed. (optional)
     - parameter audioCodec: (query) Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url&#x27;s extension. Options: aac, mp3, vorbis, wma. (optional)
     - parameter enableAutoStreamCopy: (query) Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true. (optional)
     - parameter audioSampleRate: (query) Optional. Specify a specific audio sample rate, e.g. 44100 (optional)
     - parameter audioBitRate: (query) Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults. (optional)
     - parameter audioChannels: (query) Optional. Specify a specific number of audio channels to encode to, e.g. 2 (optional)
     - parameter maxAudioChannels: (query) Optional. Specify a maximum number of audio channels to encode to, e.g. 2 (optional)
     - parameter _static: (query) Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false (optional)
     - parameter profile: (query) Optional. Specify a specific h264 profile, e.g. main, baseline, high. (optional)
     - parameter level: (query) Optional. Specify a level for the h264 profile, e.g. 3, 3.1. (optional)
     - parameter framerate: (query) Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements. (optional)
     - parameter maxFramerate: (query) Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements. (optional)
     - parameter copyTimestamps: (query) Whether or not to copy timestamps when transcoding with an offset. Defaults to false. (optional)
     - parameter startTimeTicks: (query) Optional. Specify a starting offset, in ticks. 1ms &#x3D; 10000 ticks. (optional)
     - parameter width: (query) Optional. The fixed horizontal resolution of the encoded video. (optional)
     - parameter height: (query) Optional. The fixed vertical resolution of the encoded video. (optional)
     - parameter maxWidth: (query) Optional. The maximum horizontal resolution of the encoded video. (optional)
     - parameter maxHeight: (query) Optional. The maximum vertical resolution of the encoded video. (optional)
     - parameter videoBitRate: (query) Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults. (optional)
     - parameter subtitleStreamIndex: (query) Optional. The index of the subtitle stream to use. If omitted no subtitles will be used. (optional)
     - parameter subtitleMethod: (query) Optional. Specify the subtitle delivery method. (optional)
     - parameter maxRefFrames: (query) Optional. (optional)
     - parameter maxVideoBitDepth: (query) Optional. (optional)
     - parameter videoCodec: (query) Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url&#x27;s extension. Options: h264, mpeg4, theora, vpx, wmv. (optional)
     - parameter audioStreamIndex: (query) Optional. The index of the audio stream to use. If omitted the first audio stream will be used. (optional)
     - parameter videoStreamIndex: (query) Optional. The index of the video stream to use. If omitted the first video stream will be used. (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func getVideosByIdLiveM3u8WithRequestBuilder(_id: String, container: String, deviceProfileId: String? = nil, deviceId: String? = nil, audioCodec: String? = nil, enableAutoStreamCopy: Bool? = nil, audioSampleRate: Int? = nil, audioBitRate: Int? = nil, audioChannels: Int? = nil, maxAudioChannels: Int? = nil, _static: Bool? = nil, profile: String? = nil, level: String? = nil, framerate: Float? = nil, maxFramerate: Float? = nil, copyTimestamps: Bool? = nil, startTimeTicks: Int64? = nil, width: Int? = nil, height: Int? = nil, maxWidth: Int? = nil, maxHeight: Int? = nil, videoBitRate: Int? = nil, subtitleStreamIndex: Int? = nil, subtitleMethod: SubtitleDeliveryMethod? = nil, maxRefFrames: Int? = nil, maxVideoBitDepth: Int? = nil, videoCodec: String? = nil, audioStreamIndex: Int? = nil, videoStreamIndex: Int? = nil) -> RequestBuilder<Void> {
        var path = "/Videos/{Id}/live.m3u8"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{Id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = embyclient-rest-swift-betaAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "DeviceProfileId": deviceProfileId, 
                        "DeviceId": deviceId, 
                        "Container": container, 
                        "AudioCodec": audioCodec, 
                        "EnableAutoStreamCopy": enableAutoStreamCopy, 
                        "AudioSampleRate": audioSampleRate?.encodeToJSON(), 
                        "AudioBitRate": audioBitRate?.encodeToJSON(), 
                        "AudioChannels": audioChannels?.encodeToJSON(), 
                        "MaxAudioChannels": maxAudioChannels?.encodeToJSON(), 
                        "Static": _static, 
                        "Profile": profile, 
                        "Level": level, 
                        "Framerate": framerate, 
                        "MaxFramerate": maxFramerate, 
                        "CopyTimestamps": copyTimestamps, 
                        "StartTimeTicks": startTimeTicks?.encodeToJSON(), 
                        "Width": width?.encodeToJSON(), 
                        "Height": height?.encodeToJSON(), 
                        "MaxWidth": maxWidth?.encodeToJSON(), 
                        "MaxHeight": maxHeight?.encodeToJSON(), 
                        "VideoBitRate": videoBitRate?.encodeToJSON(), 
                        "SubtitleStreamIndex": subtitleStreamIndex?.encodeToJSON(), 
                        "SubtitleMethod": subtitleMethod, 
                        "MaxRefFrames": maxRefFrames?.encodeToJSON(), 
                        "MaxVideoBitDepth": maxVideoBitDepth?.encodeToJSON(), 
                        "VideoCodec": videoCodec, 
                        "AudioStreamIndex": audioStreamIndex?.encodeToJSON(), 
                        "VideoStreamIndex": videoStreamIndex?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<Void>.Type = embyclient-rest-swift-betaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
