//
// AttributesValueCondition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Conditions for comparing with a target value.   */
public enum AttributesValueCondition: String, Codable {
    case isEqual = "IsEqual"
    case isNotEqual = "IsNotEqual"
    case isGreater = "IsGreater"
    case isGreaterOrEqual = "IsGreaterOrEqual"
    case isLess = "IsLess"
    case isLessOrEqual = "IsLessOrEqual"
}