//
// PlaybackStartInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class PlaybackStartInfo.   */

public struct PlaybackStartInfo: Codable {

    /** A value indicating whether this instance can seek. */
    public var canSeek: Bool?
    public var nowPlayingQueue: [QueueItem]?
    public var playlistItemId: String?
    /** The session id. */
    public var sessionId: String?
    /** The index of the audio stream. */
    public var audioStreamIndex: Int?
    /** The index of the subtitle stream. */
    public var subtitleStreamIndex: Int?
    /** A value indicating whether this instance is paused. */
    public var isPaused: Bool?
    public var playlistIndex: Int?
    public var playlistLength: Int?
    /** A value indicating whether this instance is muted. */
    public var isMuted: Bool?
    public var runTimeTicks: Int64?
    public var playbackStartTimeTicks: Int64?
    /** The volume level. */
    public var volumeLevel: Int?
    public var brightness: Int?
    public var aspectRatio: String?
    public var eventName: ProgressEvent?
    public var playMethod: PlayMethod?
    public var repeatMode: RepeatMode?
    public var sleepTimerMode: SleepTimerMode?
    public var sleepTimerEndTime: Date?
    public var shuffle: Bool?
    public var subtitleOffset: Int?
    public var playbackRate: Double?
    public var playlistItemIds: [String]?
    /** The play session identifier. */
    public var playSessionId: String?
    /** The item identifier. */
    public var itemId: String?
    /** The live stream identifier. */
    public var liveStreamId: String?
    /** The media version identifier. */
    public var mediaSourceId: String?
    public var item: BaseItemDto?
    /** The position ticks. */
    public var positionTicks: Int64?

    public init(canSeek: Bool? = nil, nowPlayingQueue: [QueueItem]? = nil, playlistItemId: String? = nil, sessionId: String? = nil, audioStreamIndex: Int? = nil, subtitleStreamIndex: Int? = nil, isPaused: Bool? = nil, playlistIndex: Int? = nil, playlistLength: Int? = nil, isMuted: Bool? = nil, runTimeTicks: Int64? = nil, playbackStartTimeTicks: Int64? = nil, volumeLevel: Int? = nil, brightness: Int? = nil, aspectRatio: String? = nil, eventName: ProgressEvent? = nil, playMethod: PlayMethod? = nil, repeatMode: RepeatMode? = nil, sleepTimerMode: SleepTimerMode? = nil, sleepTimerEndTime: Date? = nil, shuffle: Bool? = nil, subtitleOffset: Int? = nil, playbackRate: Double? = nil, playlistItemIds: [String]? = nil, playSessionId: String? = nil, itemId: String? = nil, liveStreamId: String? = nil, mediaSourceId: String? = nil, item: BaseItemDto? = nil, positionTicks: Int64? = nil) {
        self.canSeek = canSeek
        self.nowPlayingQueue = nowPlayingQueue
        self.playlistItemId = playlistItemId
        self.sessionId = sessionId
        self.audioStreamIndex = audioStreamIndex
        self.subtitleStreamIndex = subtitleStreamIndex
        self.isPaused = isPaused
        self.playlistIndex = playlistIndex
        self.playlistLength = playlistLength
        self.isMuted = isMuted
        self.runTimeTicks = runTimeTicks
        self.playbackStartTimeTicks = playbackStartTimeTicks
        self.volumeLevel = volumeLevel
        self.brightness = brightness
        self.aspectRatio = aspectRatio
        self.eventName = eventName
        self.playMethod = playMethod
        self.repeatMode = repeatMode
        self.sleepTimerMode = sleepTimerMode
        self.sleepTimerEndTime = sleepTimerEndTime
        self.shuffle = shuffle
        self.subtitleOffset = subtitleOffset
        self.playbackRate = playbackRate
        self.playlistItemIds = playlistItemIds
        self.playSessionId = playSessionId
        self.itemId = itemId
        self.liveStreamId = liveStreamId
        self.mediaSourceId = mediaSourceId
        self.item = item
        self.positionTicks = positionTicks
    }

    public enum CodingKeys: String, CodingKey { 
        case canSeek = "CanSeek"
        case nowPlayingQueue = "NowPlayingQueue"
        case playlistItemId = "PlaylistItemId"
        case sessionId = "SessionId"
        case audioStreamIndex = "AudioStreamIndex"
        case subtitleStreamIndex = "SubtitleStreamIndex"
        case isPaused = "IsPaused"
        case playlistIndex = "PlaylistIndex"
        case playlistLength = "PlaylistLength"
        case isMuted = "IsMuted"
        case runTimeTicks = "RunTimeTicks"
        case playbackStartTimeTicks = "PlaybackStartTimeTicks"
        case volumeLevel = "VolumeLevel"
        case brightness = "Brightness"
        case aspectRatio = "AspectRatio"
        case eventName = "EventName"
        case playMethod = "PlayMethod"
        case repeatMode = "RepeatMode"
        case sleepTimerMode = "SleepTimerMode"
        case sleepTimerEndTime = "SleepTimerEndTime"
        case shuffle = "Shuffle"
        case subtitleOffset = "SubtitleOffset"
        case playbackRate = "PlaybackRate"
        case playlistItemIds = "PlaylistItemIds"
        case playSessionId = "PlaySessionId"
        case itemId = "ItemId"
        case liveStreamId = "LiveStreamId"
        case mediaSourceId = "MediaSourceId"
        case item = "Item"
        case positionTicks = "PositionTicks"
    }

}
