//
// ProcessRunMetricsProcessStatistics.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProcessRunMetricsProcessStatistics: Codable {

    /** The current cpu. */
    public var currentCpu: Double?
    /** The average cpu. */
    public var averageCpu: Double?
    /** The currently allocated virtual memory. */
    public var currentVirtualMemory: Double?
    /** The currently allocated working set. */
    public var currentWorkingSet: Double?
    /** The metrics. */
    public var metrics: [ProcessRunMetricsProcessMetricPoint]?

    public init(currentCpu: Double? = nil, averageCpu: Double? = nil, currentVirtualMemory: Double? = nil, currentWorkingSet: Double? = nil, metrics: [ProcessRunMetricsProcessMetricPoint]? = nil) {
        self.currentCpu = currentCpu
        self.averageCpu = averageCpu
        self.currentVirtualMemory = currentVirtualMemory
        self.currentWorkingSet = currentWorkingSet
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey { 
        case currentCpu = "CurrentCpu"
        case averageCpu = "AverageCpu"
        case currentVirtualMemory = "CurrentVirtualMemory"
        case currentWorkingSet = "CurrentWorkingSet"
        case metrics = "Metrics"
    }

}
