//
// SessionPartyMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SessionPartyMessage: Codable {

    public var dateTime: Date?
    public var message: String?

    public init(dateTime: Date? = nil, message: String? = nil) {
        self.dateTime = dateTime
        self.message = message
    }

    public enum CodingKeys: String, CodingKey { 
        case dateTime = "DateTime"
        case message = "Message"
    }

}
