//
// SessionPartyInfoResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SessionPartyInfoResult: Codable {

    public var partyInfo: SessionPartyInfo?

    public init(partyInfo: SessionPartyInfo? = nil) {
        self.partyInfo = partyInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case partyInfo = "PartyInfo"
    }

}
