//
// SessionPartyInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SessionPartyInfo: Codable {

    public var _id: String?
    public var name: String?
    public var internalSessions: [SessionSessionInfo]?
    public var messages: [SessionPartyMessage]?
    public var masterSession: SessionSessionInfo?
    public var isPlaying: Bool?
    public var sessions: [SessionPartySessionInfo]?

    public init(_id: String? = nil, name: String? = nil, internalSessions: [SessionSessionInfo]? = nil, messages: [SessionPartyMessage]? = nil, masterSession: SessionSessionInfo? = nil, isPlaying: Bool? = nil, sessions: [SessionPartySessionInfo]? = nil) {
        self._id = _id
        self.name = name
        self.internalSessions = internalSessions
        self.messages = messages
        self.masterSession = masterSession
        self.isPlaying = isPlaying
        self.sessions = sessions
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case name = "Name"
        case internalSessions = "InternalSessions"
        case messages = "Messages"
        case masterSession = "MasterSession"
        case isPlaying = "IsPlaying"
        case sessions = "Sessions"
    }

}
