// <copyright file="ForgotPasswordResult.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// ForgotPasswordResult.
    /// </summary>
    /// <seealso>MediaBrowser.Model.Users.ForgotPasswordResult</seealso>
    public partial class ForgotPasswordResult :  IEquatable<ForgotPasswordResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ForgotPasswordResult" /> class.
        /// </summary>
        public ForgotPasswordResult()
        {
        }
        
        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        /// <value>The Action.</value>
        public ForgotPasswordAction Action { get; set; }

        /// <summary>
        /// The pin file.
        /// </summary>
        /// <value>The PinFile.</value>
        public string PinFile { get; set; }

        /// <summary>
        /// The pin expiration date.
        /// </summary>
        /// <value>The PinExpirationDate.</value>
        public DateTimeOffset? PinExpirationDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ForgotPasswordResult {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  PinFile: ").Append(PinFile).Append("\n");
            sb.Append("  PinExpirationDate: ").Append(PinExpirationDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ForgotPasswordResult);
        }

        /// <summary>
        /// Returns true if ForgotPasswordResult instances are equal
        /// </summary>
        /// <param name="input">Instance of ForgotPasswordResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ForgotPasswordResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.PinFile == input.PinFile ||
                    (this.PinFile != null &&
                    this.PinFile.Equals(input.PinFile))
                ) && 
                (
                    this.PinExpirationDate == input.PinExpirationDate ||
                    (this.PinExpirationDate != null &&
                    this.PinExpirationDate.Equals(input.PinExpirationDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.PinFile != null)
                    hashCode = hashCode * 59 + this.PinFile.GetHashCode();
                if (this.PinExpirationDate != null)
                    hashCode = hashCode * 59 + this.PinExpirationDate.GetHashCode();
                return hashCode;
            }
        }
    }
}