// <copyright file="SyncJobRequest.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// SyncJobRequest.
    /// </summary>
    /// <seealso>Emby.Server.Sync.Model.SyncJobRequest</seealso>
    public partial class SyncJobRequest :  IEquatable<SyncJobRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncJobRequest" /> class.
        /// </summary>
        public SyncJobRequest()
        {
        }
        
        /// <summary>
        /// Gets or Sets TargetId
        /// </summary>
        /// <value>The TargetId.</value>
        public string TargetId { get; set; }

        /// <summary>
        /// Gets or Sets ItemIds
        /// </summary>
        /// <value>The ItemIds.</value>
        public List<string> ItemIds { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        /// <value>The Category.</value>
        public SyncCategory Category { get; set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        /// <value>The ParentId.</value>
        public string ParentId { get; set; }

        /// <summary>
        /// Gets or Sets Quality
        /// </summary>
        /// <value>The Quality.</value>
        public string Quality { get; set; }

        /// <summary>
        /// Gets or Sets Profile
        /// </summary>
        /// <value>The Profile.</value>
        public string Profile { get; set; }

        /// <summary>
        /// Gets or Sets Container
        /// </summary>
        /// <value>The Container.</value>
        public string Container { get; set; }

        /// <summary>
        /// Gets or Sets VideoCodec
        /// </summary>
        /// <value>The VideoCodec.</value>
        public string VideoCodec { get; set; }

        /// <summary>
        /// Gets or Sets AudioCodec
        /// </summary>
        /// <value>The AudioCodec.</value>
        public string AudioCodec { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <value>The Name.</value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        /// <value>The UserId.</value>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets UnwatchedOnly
        /// </summary>
        /// <value>The UnwatchedOnly.</value>
        public bool? UnwatchedOnly { get; set; }

        /// <summary>
        /// Gets or Sets SyncNewContent
        /// </summary>
        /// <value>The SyncNewContent.</value>
        public bool? SyncNewContent { get; set; }

        /// <summary>
        /// Gets or Sets ItemLimit
        /// </summary>
        /// <value>The ItemLimit.</value>
        public int? ItemLimit { get; set; }

        /// <summary>
        /// Gets or Sets Bitrate
        /// </summary>
        /// <value>The Bitrate.</value>
        public int? Bitrate { get; set; }

        /// <summary>
        /// Gets or Sets Downloaded
        /// </summary>
        /// <value>The Downloaded.</value>
        public bool? Downloaded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SyncJobRequest {\n");
            sb.Append("  TargetId: ").Append(TargetId).Append("\n");
            sb.Append("  ItemIds: ").Append(ItemIds).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("  Container: ").Append(Container).Append("\n");
            sb.Append("  VideoCodec: ").Append(VideoCodec).Append("\n");
            sb.Append("  AudioCodec: ").Append(AudioCodec).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  UnwatchedOnly: ").Append(UnwatchedOnly).Append("\n");
            sb.Append("  SyncNewContent: ").Append(SyncNewContent).Append("\n");
            sb.Append("  ItemLimit: ").Append(ItemLimit).Append("\n");
            sb.Append("  Bitrate: ").Append(Bitrate).Append("\n");
            sb.Append("  Downloaded: ").Append(Downloaded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SyncJobRequest);
        }

        /// <summary>
        /// Returns true if SyncJobRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SyncJobRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SyncJobRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TargetId == input.TargetId ||
                    (this.TargetId != null &&
                    this.TargetId.Equals(input.TargetId))
                ) && 
                (
                    this.ItemIds == input.ItemIds ||
                    this.ItemIds != null &&
                    input.ItemIds != null &&
                    this.ItemIds.SequenceEqual(input.ItemIds)
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.ParentId == input.ParentId ||
                    (this.ParentId != null &&
                    this.ParentId.Equals(input.ParentId))
                ) && 
                (
                    this.Quality == input.Quality ||
                    (this.Quality != null &&
                    this.Quality.Equals(input.Quality))
                ) && 
                (
                    this.Profile == input.Profile ||
                    (this.Profile != null &&
                    this.Profile.Equals(input.Profile))
                ) && 
                (
                    this.Container == input.Container ||
                    (this.Container != null &&
                    this.Container.Equals(input.Container))
                ) && 
                (
                    this.VideoCodec == input.VideoCodec ||
                    (this.VideoCodec != null &&
                    this.VideoCodec.Equals(input.VideoCodec))
                ) && 
                (
                    this.AudioCodec == input.AudioCodec ||
                    (this.AudioCodec != null &&
                    this.AudioCodec.Equals(input.AudioCodec))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.UnwatchedOnly == input.UnwatchedOnly ||
                    (this.UnwatchedOnly != null &&
                    this.UnwatchedOnly.Equals(input.UnwatchedOnly))
                ) && 
                (
                    this.SyncNewContent == input.SyncNewContent ||
                    (this.SyncNewContent != null &&
                    this.SyncNewContent.Equals(input.SyncNewContent))
                ) && 
                (
                    this.ItemLimit == input.ItemLimit ||
                    (this.ItemLimit != null &&
                    this.ItemLimit.Equals(input.ItemLimit))
                ) && 
                (
                    this.Bitrate == input.Bitrate ||
                    (this.Bitrate != null &&
                    this.Bitrate.Equals(input.Bitrate))
                ) && 
                (
                    this.Downloaded == input.Downloaded ||
                    (this.Downloaded != null &&
                    this.Downloaded.Equals(input.Downloaded))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TargetId != null)
                    hashCode = hashCode * 59 + this.TargetId.GetHashCode();
                if (this.ItemIds != null)
                    hashCode = hashCode * 59 + this.ItemIds.GetHashCode();
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.ParentId != null)
                    hashCode = hashCode * 59 + this.ParentId.GetHashCode();
                if (this.Quality != null)
                    hashCode = hashCode * 59 + this.Quality.GetHashCode();
                if (this.Profile != null)
                    hashCode = hashCode * 59 + this.Profile.GetHashCode();
                if (this.Container != null)
                    hashCode = hashCode * 59 + this.Container.GetHashCode();
                if (this.VideoCodec != null)
                    hashCode = hashCode * 59 + this.VideoCodec.GetHashCode();
                if (this.AudioCodec != null)
                    hashCode = hashCode * 59 + this.AudioCodec.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.UnwatchedOnly != null)
                    hashCode = hashCode * 59 + this.UnwatchedOnly.GetHashCode();
                if (this.SyncNewContent != null)
                    hashCode = hashCode * 59 + this.SyncNewContent.GetHashCode();
                if (this.ItemLimit != null)
                    hashCode = hashCode * 59 + this.ItemLimit.GetHashCode();
                if (this.Bitrate != null)
                    hashCode = hashCode * 59 + this.Bitrate.GetHashCode();
                if (this.Downloaded != null)
                    hashCode = hashCode * 59 + this.Downloaded.GetHashCode();
                return hashCode;
            }
        }
    }
}