// <copyright file="UserLibraryCreditsList.cs" company="Emby LLC">
// Emby.ApiClient. Autogenerated Code. No license applied. 
// </copyright>
// <autogenerated />
namespace Emby.ApiClient.Model
{
    using System;
    using System.Linq;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;

    /// <summary>
    /// UserLibraryCreditsList.
    /// </summary>
    /// <seealso>Emby.Api.UserLibrary.CreditsList</seealso>
    public partial class UserLibraryCreditsList :  IEquatable<UserLibraryCreditsList>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLibraryCreditsList" /> class.
        /// </summary>
        public UserLibraryCreditsList()
        {
        }
        
        /// <summary>
        /// Gets or Sets PersonType
        /// </summary>
        /// <value>The PersonType.</value>
        public PersonType PersonType { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        /// <value>The Items.</value>
        public List<RemoteSearchResult> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserLibraryCreditsList {\n");
            sb.Append("  PersonType: ").Append(PersonType).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserLibraryCreditsList);
        }

        /// <summary>
        /// Returns true if UserLibraryCreditsList instances are equal
        /// </summary>
        /// <param name="input">Instance of UserLibraryCreditsList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserLibraryCreditsList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PersonType == input.PersonType ||
                    (this.PersonType != null &&
                    this.PersonType.Equals(input.PersonType))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PersonType != null)
                    hashCode = hashCode * 59 + this.PersonType.GetHashCode();
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                return hashCode;
            }
        }
    }
}